version: '3.8'

services:
  redis-master:
    image: redis:7.4
    container_name: redis-master
    networks:
      - redis-net
    command: [ "redis-server", "/usr/local/etc/redis/redis-server.conf" ]
    volumes:
      - ./redis-server.conf:/usr/local/etc/redis/redis-server.conf
    ports:
      - "6379:6379"
  redis-slave-1:
    image: redis:7.4
    container_name: redis-slave-1
    networks:
      - redis-net
    command: [ "redis-server", "/usr/local/etc/redis/redis-server.conf" ]
    depends_on:
      - redis-master
    volumes:
      - ./redis-server.conf:/usr/local/etc/redis/redis-server.conf
    ports:
      - "6380:6379"
  redis-slave-2:
    image: redis:7.4
    container_name: redis-slave-2
    networks:
      - redis-net
    command: [ "redis-server", "/usr/local/etc/redis/redis-server.conf" ]
    depends_on:
      - redis-master
    volumes:
      - ./redis-server.conf:/usr/local/etc/redis/redis-server.conf
    ports:
      - "6381:6379"
  redis-sentinel-1:
    image: redis:7.4
    container_name: redis-sentinel-1
    networks:
      - redis-net
    command: [ "redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf" ]
    depends_on:
      - redis-master
    volumes:
      - ./redis-sentinel.conf:/usr/local/etc/redis/redis-sentinel.conf
    ports:
      - "5001:26379"

  redis-sentinel-2:
    image: redis:7.4
    container_name: redis-sentinel-2
    networks:
      - redis-net
    command: [ "redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf" ]
    depends_on:
      - redis-master
    volumes:
      - ./redis-sentinel.conf:/usr/local/etc/redis/redis-sentinel.conf
    ports:
      - "5002:26379"

  redis-sentinel-3:
    image: redis:7.4
    container_name: redis-sentinel-3
    networks:
      - redis-net
    command: [ "redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf" ]
    depends_on:
      - redis-master
    volumes:
      - ./redis-sentinel.conf:/usr/local/etc/redis/redis-sentinel.conf
    ports:
      - "5003:26379"
networks:
  redis-net:
    driver: bridge