spring:
  application:
    name: redis-cache
  
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  data:
    redis:
      host: localhost
      timeout: 10000
      port: 6379

server:
  port: 8080

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
    org.tianea.rediscache: DEBUG
