spring:
  application:
    name: redis-distributed-lock
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000

server:
  port: 8080

logging:
  level:
    org:
      tianea:
        redisdistributedlock: DEBUG
      springframework:
        data:
          redis: INFO
      redisson: INFO
